### ISSUE TITLE
[Vue warn]: onMounted is called when there is no active component instance to be associated with.

### ISSUE THREAD

**Issue by delete-rain** [asvae/nuxt3-vuestic-ui#1]
down && run ->warn:
`[Vue warn]: onMounted is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup(). If you are using async setup(), make sure to register lifecycle hooks before the first await statement.`

**Comment by asvae** [comment]
We'll address it in main vuestic repo. Thanks. :)

https://github.com/epicmaxco/vuestic-ui/issues/2738
